apiVersion: 1

datasources:

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:${T_PORT_INTERN_METRICS}
    editable: false
    disableDeletion: true
    jsonData:
      timeInterval: 10s

